#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AmazonGameCircleSample.Resource", IsApplication=true)]

namespace AmazonGameCircleSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gc_overlay_spinner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rounded_corners = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int spinner_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int spinner_10 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int spinner_11 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int spinner_12 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinner_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int spinner_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int spinner_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spinner_5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spinner_6 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int spinner_7 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int spinner_8 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int spinner_9 = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int buttonShowAchievements = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int buttonShowLeaderboard = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int buttonUnlock = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int current_mood = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int go_achievements = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int go_leaderboard = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int go_whispersync = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int modal_alert_container = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int modal_overlay_container = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int new_mood = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int update_mood = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int achievements_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int leaderboard_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int modal_alert_container = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int modal_overlay_container = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int whispersync_activity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amazon_gc_prototype = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int GCAlert = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int GCOverlay = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
